"""Readiness report snapshot persistence model.

Each row is an immutable snapshot of a ReadinessReport generated by
``run_readiness_report_update`` (18:45 ET daily job).  Snapshots allow
operators to track live-mode readiness trends over time.

Phase 56 — Readiness Report History
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TimestampMixin


class ReadinessSnapshot(Base, TimestampMixin):
    """One persisted readiness report snapshot."""

    __tablename__ = "readiness_snapshots"

    id: Mapped[str] = mapped_column(sa.String(36), primary_key=True)
    # When the snapshot was generated (business time — may differ from created_at)
    captured_at: Mapped[sa.DateTime] = mapped_column(
        sa.DateTime(timezone=True), nullable=False
    )
    overall_status: Mapped[str] = mapped_column(
        sa.String(16), nullable=False
    )  # PASS | WARN | FAIL | NO_GATE
    current_mode: Mapped[str] = mapped_column(sa.String(32), nullable=False)
    target_mode: Mapped[str] = mapped_column(sa.String(32), nullable=False)
    pass_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    warn_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    fail_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    gate_count: Mapped[int] = mapped_column(
        sa.Integer, nullable=False, default=0, server_default="0"
    )
    # JSON serialization of gate rows list (gate_name, status, actual_value, …)
    gates_json: Mapped[str] = mapped_column(
        sa.Text, nullable=False, default="[]", server_default="[]"
    )
    recommendation: Mapped[str | None] = mapped_column(sa.Text, nullable=True)

    __table_args__ = (
        sa.Index("ix_readiness_snapshot_captured_at", "captured_at"),
        sa.Index("ix_readiness_snapshot_overall_status", "overall_status"),
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<ReadinessSnapshot id={self.id} status={self.overall_status!r} "
            f"captured_at={self.captured_at}>"
        )
