"""Self-improvement models: improvement_proposals, improvement_evaluations,
promoted_versions."""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Optional

import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB, UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base, TimestampMixin


class ImprovementProposal(Base, TimestampMixin):
    """Candidate change generated by the self-improvement engine."""

    __tablename__ = "improvement_proposals"
    __table_args__ = (
        sa.Index("ix_improvement_proposal_status", "status"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    proposal_timestamp: Mapped[datetime] = mapped_column(sa.DateTime, nullable=False)
    proposal_type: Mapped[str] = mapped_column(sa.String, nullable=False)
    target_component: Mapped[str] = mapped_column(sa.String, nullable=False)
    baseline_version: Mapped[Optional[str]] = mapped_column(sa.String, nullable=True)
    candidate_version: Mapped[Optional[str]] = mapped_column(sa.String, nullable=True)
    proposal_summary: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    expected_benefit: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    status: Mapped[str] = mapped_column(sa.String, nullable=False)


class ImprovementEvaluation(Base, TimestampMixin):
    """Benchmark result for a candidate improvement proposal."""

    __tablename__ = "improvement_evaluations"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    proposal_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), sa.ForeignKey("improvement_proposals.id"), nullable=False
    )
    evaluation_timestamp: Mapped[datetime] = mapped_column(sa.DateTime, nullable=False)
    result_status: Mapped[str] = mapped_column(sa.String, nullable=False)
    baseline_metrics_json: Mapped[Optional[Any]] = mapped_column(JSONB, nullable=True)
    candidate_metrics_json: Mapped[Optional[Any]] = mapped_column(JSONB, nullable=True)
    comparison_summary: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    guardrail_passed: Mapped[Optional[bool]] = mapped_column(sa.Boolean, nullable=True)


class PromotedVersion(Base, TimestampMixin):
    """Registry of accepted and promoted configs, models, and prompts."""

    __tablename__ = "promoted_versions"

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    component_type: Mapped[str] = mapped_column(sa.String, nullable=False)
    component_key: Mapped[str] = mapped_column(sa.String, nullable=False)
    version_label: Mapped[str] = mapped_column(sa.String, nullable=False)
    promotion_timestamp: Mapped[datetime] = mapped_column(sa.DateTime, nullable=False)
    promotion_reason: Mapped[Optional[str]] = mapped_column(sa.Text, nullable=True)
    rollback_reference: Mapped[Optional[str]] = mapped_column(sa.String, nullable=True)
