"""
Portfolio engine domain models (plain dataclasses, no ORM dependency).

These models represent the live in-memory portfolio truth used by:
  - portfolio_engine/service.py      — construction and sizing
  - risk_engine/service.py           — limit enforcement
  - execution_engine/service.py      — order routing
"""
from __future__ import annotations

import datetime as dt
import uuid
from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import Any

# ── Position state ────────────────────────────────────────────────────────────

@dataclass
class PortfolioPosition:
    """Live position held in the portfolio."""

    ticker: str
    quantity: Decimal
    avg_entry_price: Decimal
    current_price: Decimal
    opened_at: dt.datetime
    thesis_summary: str = ""
    strategy_key: str = ""
    security_id: object | None = None        # UUID when persisted

    @property
    def market_value(self) -> Decimal:
        return (self.quantity * self.current_price).quantize(Decimal("0.01"))

    @property
    def cost_basis(self) -> Decimal:
        return (self.quantity * self.avg_entry_price).quantize(Decimal("0.01"))

    @property
    def unrealized_pnl(self) -> Decimal:
        return self.market_value - self.cost_basis

    @property
    def unrealized_pnl_pct(self) -> Decimal:
        if self.cost_basis == Decimal("0"):
            return Decimal("0")
        return (self.unrealized_pnl / self.cost_basis).quantize(Decimal("0.000001"))


# ── Portfolio aggregate state ─────────────────────────────────────────────────

@dataclass
class PortfolioState:
    """Mutable in-memory representation of the full portfolio.

    start_of_day_equity and high_water_mark should be seeded at session start
    from the most recent PortfolioSnapshot persisted to the DB.
    """

    cash: Decimal
    positions: dict[str, PortfolioPosition] = field(default_factory=dict)
    start_of_day_equity: Decimal | None = None    # for daily P&L limit
    start_of_month_equity: Decimal | None = None  # for monthly drawdown limit
    high_water_mark: Decimal | None = None         # for weekly drawdown limit
    daily_opens_count: int = 0                        # new OPEN fills today; reset to 0 at start of each day

    @property
    def gross_exposure(self) -> Decimal:
        return sum(
            (p.market_value for p in self.positions.values()), Decimal("0")
        )

    @property
    def equity(self) -> Decimal:
        return self.cash + self.gross_exposure

    @property
    def position_count(self) -> int:
        return len(self.positions)

    @property
    def drawdown_pct(self) -> Decimal:
        """Fraction below high-water mark (0 = at peak, 0.10 = 10% drawdown)."""
        if not self.high_water_mark or self.high_water_mark == Decimal("0"):
            return Decimal("0")
        decline = self.high_water_mark - self.equity
        if decline <= Decimal("0"):
            return Decimal("0")
        return (decline / self.high_water_mark).quantize(Decimal("0.0001"))

    @property
    def daily_pnl_pct(self) -> Decimal:
        """Daily P&L as a fraction of start-of-day equity (negative = loss)."""
        if not self.start_of_day_equity or self.start_of_day_equity == Decimal("0"):
            return Decimal("0")
        return (
            (self.equity - self.start_of_day_equity) / self.start_of_day_equity
        ).quantize(Decimal("0.0001"))

    @property
    def monthly_pnl_pct(self) -> Decimal:
        """Month-to-date P&L as a fraction of start-of-month equity (negative = loss)."""
        if not self.start_of_month_equity or self.start_of_month_equity == Decimal("0"):
            return Decimal("0")
        return (
            (self.equity - self.start_of_month_equity) / self.start_of_month_equity
        ).quantize(Decimal("0.0001"))


# ── Portfolio actions ─────────────────────────────────────────────────────────

class ActionType(str, Enum):
    OPEN = "open"
    CLOSE = "close"
    TRIM = "trim"        # partial size reduction; target_quantity specifies shares to sell
    BLOCKED = "blocked"  # risk engine blocked this action


@dataclass
class PortfolioAction:
    """A proposed portfolio operation generated by PortfolioEngineService.

    Before execution this must be validated by RiskEngineService.
    After validation, risk_approved must be set to True before submitting
    to ExecutionEngineService.
    """

    action_type: ActionType
    ticker: str
    reason: str
    target_notional: Decimal = Decimal("0")
    target_quantity: Decimal | None = None   # shares; may be None until execution
    thesis_summary: str = ""
    sizing_rationale: str = ""
    risk_approved: bool = False
    security_id: object | None = None        # UUID when available
    ranked_result: Any | None = None         # RankedResult for full traceability
    id: str = field(default_factory=lambda: str(uuid.uuid4()))  # unique action identifier


# ── Closed trade ledger ──────────────────────────────────────────────────────

@dataclass
class ClosedTrade:
    """Immutable record of a completed position exit (CLOSE) or partial trim (TRIM).

    Created in the paper trading cycle immediately after a CLOSE/TRIM fill,
    before the broker sync removes the position from portfolio state.
    Used by the trade history API and daily P&L reporting.
    """

    ticker: str
    action_type: ActionType          # CLOSE or TRIM
    fill_price: Decimal              # actual execution price per share
    avg_entry_price: Decimal         # position's average entry price at close time
    quantity: Decimal                # shares sold / trimmed
    realized_pnl: Decimal            # (fill_price - avg_entry_price) * quantity
    realized_pnl_pct: Decimal        # realized_pnl / (avg_entry_price * quantity)
    reason: str                      # trigger: "not_in_buy_set", "stop_loss", etc.
    opened_at: dt.datetime
    closed_at: dt.datetime
    hold_duration_days: int          # calendar days from open to close

    @property
    def is_winner(self) -> bool:
        """True when the trade produced a positive realized P&L."""
        return self.realized_pnl > Decimal("0")


# ── Sizing ────────────────────────────────────────────────────────────────────

@dataclass
class SizingResult:
    """Output from PortfolioEngineService.compute_sizing()."""

    target_notional: Decimal
    target_pct: Decimal          # fraction of portfolio equity
    half_kelly_pct: Decimal      # raw half-Kelly fraction (pre-cap)
    capped: bool                 # True if half_kelly was clipped by a ceiling
    rationale: str


# ── Snapshot ──────────────────────────────────────────────────────────────────

@dataclass
class PortfolioSnapshot:
    """Point-in-time summary of portfolio state, suitable for persistence."""

    snapshot_at: dt.datetime
    cash: Decimal
    equity: Decimal
    gross_exposure: Decimal
    position_count: int
    drawdown_pct: Decimal
    daily_pnl_pct: Decimal
    positions: list[PortfolioPosition]
    mode: str = "paper"

