"""
Self-Improvement Engine domain models (plain dataclasses, no ORM dependency).

These models represent the lifecycle of a controlled improvement proposal:
  1. ImprovementProposal  — a candidate change with metadata
  2. ProposalEvaluation   — challenger vs baseline metric comparison
  3. PromotionDecision    — final accept/reject record (promotion guard)

They feed:
  - self_improvement/service.py  — computation
  - tests/unit/test_self_improvement.py  — Gate E QA

Guardrail constants
-------------------
PROTECTED_COMPONENTS: components whose core logic may never be auto-promoted.
ALLOWED_PROPOSAL_TYPES: the only kinds of changes the engine is permitted to
    generate; anything else is rejected at proposal-creation time.
"""
from __future__ import annotations

import datetime as dt
import uuid
from dataclasses import dataclass, field
from decimal import Decimal
from enum import Enum
from typing import Any, Optional


# ── Allowed change scope ───────────────────────────────────────────────────────

class ProposalType(str, Enum):
    """Types of parameters the self-improvement engine may propose changes to.

    Per spec §13.1 — the engine MAY adjust these.
    """
    PROMPT_TEMPLATE         = "prompt_template"
    FEATURE_TRANSFORMATION  = "feature_transformation"
    SOURCE_WEIGHT           = "source_weight"
    RANKING_THRESHOLD       = "ranking_threshold"
    CONFIDENCE_CALIBRATION  = "confidence_calibration"
    SIZING_FORMULA          = "sizing_formula"
    HOLDING_PERIOD_RULE     = "holding_period_rule"
    REGIME_CLASSIFIER       = "regime_classifier"


# Components whose core safety rules may NOT be auto-promoted (spec §13.2).
PROTECTED_COMPONENTS: frozenset[str] = frozenset({
    "risk_engine",
    "execution_engine",
    "broker_adapter",
    "capital_allocation",
    "live_trading_permissions",
})


class ProposalStatus(str, Enum):
    PENDING    = "pending"       # created, not yet evaluated
    EVALUATED  = "evaluated"     # evaluation complete, awaiting decision
    PROMOTED   = "promoted"      # accepted and entered version registry
    REJECTED   = "rejected"      # declined (guardrail or metric failure)


# ── Core models ────────────────────────────────────────────────────────────────

@dataclass
class ImprovementProposal:
    """A candidate change generated by the self-improvement engine.

    Mirrors `improvement_proposals` DB table (spec §11.1) but lives in memory.
    """
    proposal_type: ProposalType
    target_component: str
    baseline_version: str
    candidate_version: str
    proposal_summary: str
    expected_benefit: str

    # Filled automatically on creation
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    proposal_timestamp: dt.datetime = field(
        default_factory=lambda: dt.datetime.now(dt.timezone.utc)
    )
    status: ProposalStatus = ProposalStatus.PENDING

    # Optional: structured parameter diffs
    baseline_params: dict[str, Any] = field(default_factory=dict)
    candidate_params: dict[str, Any] = field(default_factory=dict)

    # Phase 36: confidence score computed by SelfImprovementService.promote_or_reject()
    # Range [0.0, 1.0]; used by AutoExecutionService to gate auto-execution.
    confidence_score: float = 0.0

    @property
    def is_protected(self) -> bool:
        """True when the target component is on the protected list."""
        return self.target_component in PROTECTED_COMPONENTS


@dataclass
class ProposalEvaluation:
    """Challenger-vs-baseline metric comparison for one proposal.

    Mirrors `improvement_evaluations` DB table (spec §11.2).
    All metric values are fractional unless noted.
    """
    proposal_id: str
    baseline_metrics: dict[str, Decimal]    # e.g. {"hit_rate": 0.55, "sharpe": 1.1}
    candidate_metrics: dict[str, Decimal]   # same keys, challenger values
    comparison_summary: str
    guardrail_passed: bool

    # Filled automatically
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    evaluation_timestamp: dt.datetime = field(
        default_factory=lambda: dt.datetime.now(dt.timezone.utc)
    )
    result_status: str = "pending"          # "pass" | "fail" | "inconclusive"

    @property
    def metric_deltas(self) -> dict[str, Decimal]:
        """candidate - baseline for each shared metric key."""
        return {
            k: (self.candidate_metrics.get(k, Decimal("0"))
                - self.baseline_metrics.get(k, Decimal("0")))
            for k in self.baseline_metrics
        }

    @property
    def improvement_count(self) -> int:
        """Number of metrics where the candidate outperforms the baseline."""
        return sum(1 for delta in self.metric_deltas.values() if delta > Decimal("0"))

    @property
    def regression_count(self) -> int:
        """Number of metrics where the candidate underperforms the baseline."""
        return sum(1 for delta in self.metric_deltas.values() if delta < Decimal("0"))


@dataclass
class PromotionDecision:
    """Final accept/reject record — the promotion guard output.

    Mirrors `promoted_versions` DB table (spec §11.3) for accepted proposals,
    and the audit trail for rejected ones.

    Per spec §4.5: no strategy or model promotes itself directly.
    The promotion guard is the only path to acceptance.
    """
    proposal_id: str
    accepted: bool
    decision_reason: str
    promoted_version_label: Optional[str]   # filled only when accepted=True
    rollback_reference: Optional[str]        # version to roll back to if needed

    # Filled automatically
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    decision_timestamp: dt.datetime = field(
        default_factory=lambda: dt.datetime.now(dt.timezone.utc)
    )
    component_type: str = ""
    component_key: str = ""
