"""
Route handlers for /api/v1/system/readiness-report (Phases 53 + 56).

Provides a cached pre-computed live-mode readiness snapshot and history.

Endpoints
---------
  GET  /api/v1/system/readiness-report
      Returns the latest cached ReadinessReport generated by
      ``run_readiness_report_update`` (18:45 ET daily job).
      Returns 503 when no report has been computed yet.

  GET  /api/v1/system/readiness-report/history
      Returns up to *limit* persisted ReadinessSnapshot rows from DB,
      newest-first. Returns 200 + empty list when no snapshots exist.
      Degrades gracefully to empty list when DB is unavailable.

Design notes
------------
- Read-only: no mutations, no broker calls, no DB writes.
- The report is pre-computed by the evening job; this endpoint just
  serves the cache.  Operators who need a fresh on-demand evaluation
  should call GET /api/v1/live-gate/status (which re-evaluates live).
"""
from __future__ import annotations

from fastapi import APIRouter, HTTPException, Query

from apps.api.deps import AppStateDep
from apps.api.schemas.readiness import (
    ReadinessGateRowSchema,
    ReadinessHistoryResponse,
    ReadinessReportResponse,
    ReadinessSnapshotSchema,
)

readiness_router = APIRouter(tags=["Readiness"])


def _serialize_report(report) -> ReadinessReportResponse:
    """Convert a ReadinessReport dataclass to the API response schema."""
    rows = [
        ReadinessGateRowSchema(
            gate_name=r.gate_name,
            description=r.description,
            status=r.status,
            actual_value=r.actual_value,
            required_value=r.required_value,
            detail=r.detail,
        )
        for r in report.gate_rows
    ]
    return ReadinessReportResponse(
        generated_at=report.generated_at.isoformat(),
        current_mode=report.current_mode,
        target_mode=report.target_mode,
        overall_status=report.overall_status,
        gate_rows=rows,
        gate_count=report.gate_count,
        pass_count=report.pass_count,
        warn_count=report.warn_count,
        fail_count=report.fail_count,
        recommendation=report.recommendation,
        is_ready=report.is_ready,
    )


@readiness_router.get(
    "/system/readiness-report",
    response_model=ReadinessReportResponse,
    summary="Get cached live-mode readiness report",
)
async def get_readiness_report(state: AppStateDep) -> ReadinessReportResponse:
    """Return the latest pre-computed live-mode readiness snapshot.

    The report is generated daily at 18:45 ET by ``run_readiness_report_update``
    and reflects all live-gate requirements with PASS / WARN / FAIL status.

    Returns 503 when no report has been computed yet (job has not run today).
    For a live evaluation, use GET /api/v1/live-gate/status instead.
    """
    report = getattr(state, "latest_readiness_report", None)
    if report is None:
        raise HTTPException(
            status_code=503,
            detail=(
                "No readiness report available yet. "
                "The run_readiness_report_update job runs at 18:45 ET on weekdays. "
                "For an on-demand evaluation, call GET /api/v1/live-gate/status."
            ),
        )
    return _serialize_report(report)


@readiness_router.get(
    "/system/readiness-report/history",
    response_model=ReadinessHistoryResponse,
    summary="Readiness report snapshot history",
)
async def get_readiness_history(
    state: AppStateDep,
    limit: int = Query(
        default=10, ge=1, le=100, description="Maximum number of snapshots to return"
    ),
) -> ReadinessHistoryResponse:
    """Return up to *limit* persisted readiness snapshots, newest-first.

    Snapshots are written daily by ``run_readiness_report_update`` (18:45 ET).
    Returns HTTP 200 + empty list when no snapshots exist or the DB is unavailable.
    """
    try:
        import sqlalchemy as sa
        from infra.db.models.readiness import ReadinessSnapshot
        from infra.db.session import SessionLocal

        with SessionLocal() as session:
            rows = (
                session.execute(
                    sa.select(ReadinessSnapshot)
                    .order_by(ReadinessSnapshot.captured_at.desc())
                    .limit(limit)
                )
                .scalars()
                .all()
            )

        snapshots = [
            ReadinessSnapshotSchema(
                id=row.id,
                captured_at=row.captured_at.isoformat() if row.captured_at else "",
                overall_status=row.overall_status,
                current_mode=row.current_mode,
                target_mode=row.target_mode,
                pass_count=row.pass_count,
                warn_count=row.warn_count,
                fail_count=row.fail_count,
                gate_count=row.gate_count,
                recommendation=row.recommendation,
            )
            for row in rows
        ]
        return ReadinessHistoryResponse(snapshots=snapshots, count=len(snapshots))

    except Exception:  # noqa: BLE001
        # Graceful degradation: DB unavailable → return empty history
        return ReadinessHistoryResponse(snapshots=[], count=0)
