"""initial_schema

Revision ID: 9ed5639351bb
Revises:
Create Date: 2026-03-17 19:32:42.016585

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ed5639351bb'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_timestamp', sa.DateTime(), nullable=False),
    sa.Column('decision_type', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('evaluation_period_start', sa.Date(), nullable=True),
    sa.Column('evaluation_period_end', sa.Date(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('benchmark_set', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_run_timestamp', 'evaluation_runs', ['run_timestamp'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_key', sa.String(), nullable=False),
    sa.Column('feature_name', sa.String(), nullable=False),
    sa.Column('feature_group', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_key')
    )
    op.create_table('improvement_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_timestamp', sa.DateTime(), nullable=False),
    sa.Column('proposal_type', sa.String(), nullable=False),
    sa.Column('target_component', sa.String(), nullable=False),
    sa.Column('baseline_version', sa.String(), nullable=True),
    sa.Column('candidate_version', sa.String(), nullable=True),
    sa.Column('proposal_summary', sa.Text(), nullable=True),
    sa.Column('expected_benefit', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_improvement_proposal_status', 'improvement_proposals', ['status'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('snapshot_timestamp', sa.DateTime(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('gross_exposure', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('net_exposure', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('equity_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('drawdown_pct', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promoted_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('component_key', sa.String(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('promotion_timestamp', sa.DateTime(), nullable=False),
    sa.Column('promotion_reason', sa.Text(), nullable=True),
    sa.Column('rollback_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_ticker'), 'securities', ['ticker'], unique=True)
    op.create_table('session_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_timestamp', sa.DateTime(), nullable=False),
    sa.Column('capacity_trigger', sa.String(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('current_status', sa.Text(), nullable=True),
    sa.Column('files_changed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('qa_status', sa.String(), nullable=True),
    sa.Column('open_items_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('continuity_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('run_mode', sa.String(), nullable=False),
    sa.Column('universe_name', sa.String(), nullable=True),
    sa.Column('config_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('reliability_tier', sa.String(), nullable=False),
    sa.Column('default_weight', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_table('strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_key', sa.String(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_family', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_key')
    )
    op.create_table('themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme_key', sa.String(), nullable=False),
    sa.Column('theme_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('theme_key')
    )
    op.create_table('daily_market_bars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adjusted_close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('vwap', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'trade_date', name='uq_daily_bar_security_date')
    )
    op.create_index('ix_daily_bar_security_date', 'daily_market_bars', ['security_id', 'trade_date'], unique=False)
    op.create_table('evaluation_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('metric_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('improvement_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('result_status', sa.String(), nullable=False),
    sa.Column('baseline_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('candidate_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comparison_summary', sa.Text(), nullable=True),
    sa.Column('guardrail_passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['improvement_proposals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_attribution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_run_id', sa.UUID(), nullable=False),
    sa.Column('attribution_type', sa.String(), nullable=False),
    sa.Column('attribution_key', sa.String(), nullable=False),
    sa.Column('attribution_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('cost_basis', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('strategy_id', sa.UUID(), nullable=True),
    sa.Column('thesis_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_position_status', 'positions', ['status'], unique=False)
    op.create_table('ranking_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_run_id', sa.UUID(), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(), nullable=False),
    sa.Column('config_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_run_id'], ['signal_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_feature_values',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('feature_id', sa.UUID(), nullable=False),
    sa.Column('as_of_timestamp', sa.DateTime(), nullable=False),
    sa.Column('feature_value_numeric', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('feature_value_text', sa.Text(), nullable=True),
    sa.Column('source_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sfv_feature_timestamp', 'security_feature_values', ['feature_id', 'as_of_timestamp'], unique=False)
    op.create_index('ix_sfv_security_timestamp', 'security_feature_values', ['security_id', 'as_of_timestamp'], unique=False)
    op.create_table('security_liquidity_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('avg_dollar_volume_20d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('avg_share_volume_20d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('atr_14', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('volatility_20d', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('float_shares', sa.BigInteger(), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'metric_date', name='uq_liquidity_security_date')
    )
    op.create_table('security_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_run_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('strategy_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.String(), nullable=False),
    sa.Column('signal_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('catalyst_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('liquidity_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('horizon_classification', sa.String(), nullable=True),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['signal_run_id'], ['signal_runs.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signal_run_security', 'security_signals', ['signal_run_id', 'security_id'], unique=False)
    op.create_table('security_themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('source_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('raw_payload_ref', sa.Text(), nullable=True),
    sa.Column('credibility_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('decay_score', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_events_event_timestamp'), 'source_events', ['event_timestamp'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('broker_order_ref', sa.String(), nullable=True),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('order_timestamp', sa.DateTime(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('notional_amount', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('decision_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_status', 'orders', ['status'], unique=False)
    op.create_table('ranked_opportunities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ranking_run_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('composite_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('portfolio_fit_score', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('recommended_action', sa.String(), nullable=False),
    sa.Column('target_horizon', sa.String(), nullable=True),
    sa.Column('thesis_summary', sa.Text(), nullable=True),
    sa.Column('disconfirming_factors', sa.Text(), nullable=True),
    sa.Column('sizing_hint_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ranking_run_id'], ['ranking_runs.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ranked_opp_run_rank', 'ranked_opportunities', ['ranking_run_id', 'rank_position'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=True),
    sa.Column('position_id', sa.UUID(), nullable=True),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_event_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_event_id', sa.UUID(), nullable=False),
    sa.Column('security_id', sa.UUID(), nullable=False),
    sa.Column('link_reason', sa.String(), nullable=True),
    sa.Column('impact_direction', sa.String(), nullable=True),
    sa.Column('impact_confidence', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.ForeignKeyConstraint(['source_event_id'], ['source_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('fill_timestamp', sa.DateTime(), nullable=False),
    sa.Column('fill_quantity', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('fill_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('fees', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('liquidity_flag', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fill_timestamp', 'fills', ['fill_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fill_timestamp', table_name='fills')
    op.drop_table('fills')
    op.drop_table('security_event_links')
    op.drop_table('risk_events')
    op.drop_index('ix_ranked_opp_run_rank', table_name='ranked_opportunities')
    op.drop_table('ranked_opportunities')
    op.drop_index('ix_order_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_source_events_event_timestamp'), table_name='source_events')
    op.drop_table('source_events')
    op.drop_table('security_themes')
    op.drop_index('ix_signal_run_security', table_name='security_signals')
    op.drop_table('security_signals')
    op.drop_table('security_liquidity_metrics')
    op.drop_index('ix_sfv_security_timestamp', table_name='security_feature_values')
    op.drop_index('ix_sfv_feature_timestamp', table_name='security_feature_values')
    op.drop_table('security_feature_values')
    op.drop_table('ranking_runs')
    op.drop_index('ix_position_status', table_name='positions')
    op.drop_table('positions')
    op.drop_table('performance_attribution')
    op.drop_table('improvement_evaluations')
    op.drop_table('evaluation_metrics')
    op.drop_index('ix_daily_bar_security_date', table_name='daily_market_bars')
    op.drop_table('daily_market_bars')
    op.drop_table('themes')
    op.drop_table('strategies')
    op.drop_table('sources')
    op.drop_table('signal_runs')
    op.drop_table('session_checkpoints')
    op.drop_index(op.f('ix_securities_ticker'), table_name='securities')
    op.drop_table('securities')
    op.drop_table('promoted_versions')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_improvement_proposal_status', table_name='improvement_proposals')
    op.drop_table('improvement_proposals')
    op.drop_table('features')
    op.drop_index('ix_eval_run_timestamp', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_table('decision_audit')
    # ### end Alembic commands ###
