"""
yfinance market-data adapter.

Responsibility: fetch raw OHLCV bars via yfinance and normalise them into
BarRecord objects.  All I/O happens here; no DB access.

Reliability tag: "yfinance" — classified as a *secondary verified* source
(delayed/EOD data, equity markets only).  Rumours and unverified events are
never generated by this adapter.
"""
from __future__ import annotations

import datetime as dt
import logging
from decimal import Decimal, InvalidOperation
from typing import Optional

import pandas as pd

from services.data_ingestion.models import BarRecord

logger = logging.getLogger(__name__)

# Reliability classification used by the ranking layer (Gate B: sources tagged)
SOURCE_KEY = "yfinance"
RELIABILITY_TIER = "secondary_verified"   # delayed EOD, no real-time


def _to_decimal(value: object) -> Optional[Decimal]:
    """Safely convert a pandas or Python scalar to Decimal."""
    if value is None:
        return None
    try:
        import math
        if isinstance(value, float) and math.isnan(value):
            return None
        return Decimal(str(value))
    except (InvalidOperation, ValueError):
        return None


def _to_int(value: object) -> Optional[int]:
    if value is None:
        return None
    try:
        import math
        if isinstance(value, float) and math.isnan(value):
            return None
        return int(value)
    except (TypeError, ValueError):
        return None


class YFinanceAdapter:
    """Fetches and normalises daily OHLCV data from Yahoo Finance.

    Usage::

        adapter = YFinanceAdapter()
        bars = adapter.fetch_bars("AAPL", period="1y")
        bulk = adapter.fetch_bulk(["AAPL", "MSFT"], period="6mo")
    """

    SOURCE_KEY: str = SOURCE_KEY
    RELIABILITY_TIER: str = RELIABILITY_TIER

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def fetch_bars(
        self,
        ticker: str,
        *,
        period: str = "1y",
        start: Optional[dt.date] = None,
        end: Optional[dt.date] = None,
    ) -> list[BarRecord]:
        """Fetch daily bars for a single ticker.

        Args:
            ticker: e.g. "AAPL"
            period: yfinance period string (ignored when start/end provided)
            start:  inclusive start date
            end:    inclusive end date

        Returns:
            List of BarRecord sorted ascending by trade_date.
            Returns an empty list on any error (logged as WARNING).
        """
        import yfinance as yf  # import here to keep module importable when yfinance absent

        try:
            ticker_obj = yf.Ticker(ticker)
            if start and end:
                df = ticker_obj.history(
                    start=start.isoformat(),
                    end=(end + dt.timedelta(days=1)).isoformat(),
                    auto_adjust=False,
                )
            else:
                df = ticker_obj.history(period=period, auto_adjust=False)

            if df is None or df.empty:
                logger.warning("yfinance returned no data for %s (period=%s)", ticker, period)
                return []

            return self._normalise_df(ticker, df)

        except Exception as exc:  # noqa: BLE001
            logger.warning("yfinance fetch failed for %s: %s", ticker, exc)
            return []

    def fetch_bulk(
        self,
        tickers: list[str],
        *,
        period: str = "1y",
        start: Optional[dt.date] = None,
        end: Optional[dt.date] = None,
    ) -> dict[str, list[BarRecord]]:
        """Fetch daily bars for multiple tickers in a single yfinance call.

        Returns a dict of ticker → list[BarRecord].  Missing/error tickers
        map to an empty list.
        """
        import yfinance as yf

        if not tickers:
            return {}

        try:
            if start and end:
                raw = yf.download(
                    tickers,
                    start=start.isoformat(),
                    end=(end + dt.timedelta(days=1)).isoformat(),
                    auto_adjust=False,
                    group_by="ticker",
                    progress=False,
                    threads=True,
                )
            else:
                raw = yf.download(
                    tickers,
                    period=period,
                    auto_adjust=False,
                    group_by="ticker",
                    progress=False,
                    threads=True,
                )
        except Exception as exc:  # noqa: BLE001
            logger.warning("yfinance bulk download failed: %s", exc)
            return {t: [] for t in tickers}

        results: dict[str, list[BarRecord]] = {}

        if len(tickers) == 1:
            # yfinance returns flat columns for single ticker
            results[tickers[0]] = self._normalise_df(tickers[0], raw)
        else:
            for ticker in tickers:
                try:
                    if ticker not in raw.columns.get_level_values(0):
                        results[ticker] = []
                        continue
                    df_t = raw[ticker].copy()
                    results[ticker] = self._normalise_df(ticker, df_t)
                except Exception as exc:  # noqa: BLE001
                    logger.warning("normalise failed for %s: %s", ticker, exc)
                    results[ticker] = []

        return results

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _normalise_df(self, ticker: str, df: pd.DataFrame) -> list[BarRecord]:
        """Map a raw yfinance DataFrame to a list of BarRecord."""
        records: list[BarRecord] = []
        # Ensure the index is a DatetimeIndex / date-parsable
        df = df.dropna(subset=["Close"])

        for idx, row in df.iterrows():
            try:
                if hasattr(idx, "date"):
                    trade_date = idx.date()
                else:
                    trade_date = pd.Timestamp(idx).date()

                # yfinance column names differ by version; normalise
                close = _to_decimal(row.get("Close") or row.get("close"))
                adj_close = _to_decimal(row.get("Adj Close") or row.get("adj_close") or row.get("Close"))
                records.append(
                    BarRecord(
                        ticker=ticker,
                        trade_date=trade_date,
                        open=_to_decimal(row.get("Open") or row.get("open")),
                        high=_to_decimal(row.get("High") or row.get("high")),
                        low=_to_decimal(row.get("Low") or row.get("low")),
                        close=close,
                        adjusted_close=adj_close,
                        volume=_to_int(row.get("Volume") or row.get("volume")),
                        source_key=SOURCE_KEY,
                    )
                )
            except Exception as exc:  # noqa: BLE001
                logger.debug("Skipping malformed row for %s at %s: %s", ticker, idx, exc)

        records.sort(key=lambda b: b.trade_date)
        return records
